### PR TITLE
docs: add custom decorator update-example-dates

### PR DESCRIPTION
**Pull request by tatomyr**
A custom decorator to substitute simple datetime templates in examples.

### CODE REVIEW

**Review by RomanHotsiy — APPROVED** [review]
LGTM 👍

**Review by lornajane — COMMENTED** [review]
This is neat and it works perfectly for me!

If it's OK with you, I'd like to reframe the words to explain the problem it solves (short version: add a special placeholder and use a decorator to put in an appropriate value at bundle time - I think the replacement piece is more important than the datetime element).

Also, I note that this needs to be added to the main README.

**Comment by lornajane** [comment]
You pushed a change while I was typing :)

**Comment by tatomyr** [comment]
> I'd like to reframe the words to explain the problem it solves

Please do! I'll refrain from pushing any more changes.

**Pull request merged**
